config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :movies, except: [:create, :new]
  resources :lists
  resources :bookmarks, only: [:new, :create, :delete]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :restrict_with_exception
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.save
    redirect_to lists_path(@list)
  end

  private

  def bookmark_params
    params.require(@bookmark).permit(@list, :movie)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @movies = @list.movies
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>Bookmarks#new</h1>
<p>Find me in app/views/bookmarks/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1 class="m-2">Lists</h1>
<br>
<%= link_to "New list", new_list_path, :class => "btn btn-primary p-1 m-2" %>
<br>
<ul class="list-group">
  <% @lists.each do |list| %>
    <ul class="list-group-item">
      <%= link_to list.name, list_path(list) %>
    </ul>
  <% end %>
</ul>

app/views/lists/new.html.erb
<h1 class="m-2">New List</h1>
<div class="container">
  <%= simple_form_for @list do |f| %>
    <%= f.input :name, label: "List name" %>
    <%= f.submit "Create", class: "btn btn-primary p-1 m-2" %>
  <% end %>
</div>
<hr>
<%= link_to "Back to all lists", lists_path, :class => "btn btn-primary p-1 m-2" %>

app/views/lists/show.html.erb
<div class="m-2">
  <h1><%= @list.name %></h1>
</div>

<ul class="list-group">
  <% @movies.each do |movie| %>
    <ul class="list-group-item">
      <%= link_to movie.title, movie_path(movie) %>
    </ul>
  <% end %>
</ul>
<hr>
<%= link_to "Back to all lists", lists_path, :class => "btn btn-primary p-1 m-2" %>